// TSEB Supabase Configuration
const SUPABASE_URL = 'https://vezlljkdmgibkbszlgvl.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlemxsamtkbWdpYmtic3psZ3ZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIzMDI5OTgsImV4cCI6MjA4Nzg3ODk5OH0.AZvWAn0nImLjlWw9gUVMeCDGGEGrdakTRkZuTmRbt4g';
